
import MyContext from './Helper/Context'
import Header from './component/Header'
import TopHeader from './component/TopHeader'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body>
        <TopHeader />
        <Header />
        <MyContext>
        {children}
        </MyContext>
        </body>
    </html>
  )
}
